{"name": "test_basic_auth_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 503 == 401\n +  where 503 = <Response [503]>.status_code", "trace": "def test_basic_auth_failure():\n        response = requests.get(f\"{HTTPBIN}/basic-auth/user/passwd\", auth=(\"user\", \"wrong\"))\n>       assert response.status_code == 401  # deve dar nao autorizado\nE       assert 503 == 401\nE        +  where 503 = <Response [503]>.status_code\n\ntest/test_api2.py:107: AssertionError"}, "start": 1760964036918, "stop": 1760964037473, "uuid": "6d9e65a5-1422-4bd1-a077-5f9c36e5dafd", "historyId": "2241fab8bcaa33e1ac48da3e8fced99c", "testCaseId": "2241fab8bcaa33e1ac48da3e8fced99c", "fullName": "test.test_api2#test_basic_auth_failure", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api2"}, {"name": "host", "value": "EU314602016234.local"}, {"name": "thread", "value": "5604-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api2"}], "titlePath": ["test", "test_api2.py"]}