{"name": "test_basic_auth_failure", "status": "failed", "statusDetails": {"message": "AssertionError: assert 503 == 401\n +  where 503 = <Response [503]>.status_code", "trace": "def test_basic_auth_failure():\n        response = requests.get(f\"{HTTPBIN}/basic-auth/user/passwd\", auth=(\"user\", \"wrong\"))\n>       assert response.status_code == 401  # deve dar nao autorizado\nE       assert 503 == 401\nE        +  where 503 = <Response [503]>.status_code\n\ntest/test_api2.py:107: AssertionError"}, "start": 1760968749662, "stop": 1760968750112, "uuid": "f61f7e0e-8ce1-4a57-9068-4be7b6bb7e03", "historyId": "2241fab8bcaa33e1ac48da3e8fced99c", "testCaseId": "2241fab8bcaa33e1ac48da3e8fced99c", "fullName": "test.test_api2#test_basic_auth_failure", "labels": [{"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "test_api2"}, {"name": "host", "value": "EU314602016234.local"}, {"name": "thread", "value": "6574-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.test_api2"}], "titlePath": ["test", "test_api2.py"]}